# Generated by Django 4.2 on 2024-03-20 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="chat_id",
            field=models.CharField(
                blank=True,
                max_length=128,
                null=True,
                verbose_name="ID пользователя telegram",
            ),
        ),
    ]
