version: '3.8'


services:
  nginx:
    build: ./nginx
    ports:
      - 8080:80
    volumes:
      - static:/app/static
      - media:/app/media
    depends_on:
      - backend

  celery:
    command: celery -A config worker -l info -c 1 -Q celery
    build:
      context: ./backend
    env_file:
      - .env
    environment:
      - CELERY_BROKER_URL=$CELERY_BROKER_URL
      - CELERY_RESULT_BACKEND=$CELERY_RESULT_BACKEND
    depends_on:
      - db
      - redis

  celery-beat:
    command: celery -A config worker -l info -E -B
    build:
      context: ./backend
    env_file:
      - .env
    environment:
      - CELERY_BROKER_URL=$CELERY_BROKER_URL
      - CELERY_RESULT_BACKEND=$CELERY_RESULT_BACKEND
    depends_on:
      - db
      - redis

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    volumes:
      - static:/app/static
      - media:/app/media
    env_file:
      - ./.env
    environment:
      - DEBUG=false
    depends_on:
      - db

  db:
    image: postgres:16.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_NAME=$POSTGRES_NAME

  redis:
    image: redis:6.2-alpine
    volumes:
      - redisdata:/data


volumes:
  postgres_data:
  redisdata:
  static:
  media: