# Generated by Django 4.2 on 2024-03-24 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0003_remove_habit_habit_nice_no_related_habit_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="habit",
            options={
                "ordering": ["id"],
                "verbose_name": "Привычка",
                "verbose_name_plural": "Привычки",
            },
        ),
    ]
